require('william.plugins-setup')
require('william.core.options')
require('william.core.keymaps')
require('william.core.colorscheme')

require("william.plugins.comment")
require("william.plugins.nvim-tree")
require("william.plugins.lualine")
require("william.plugins.telescope")
require("william.plugins.nvim-cmp")
require("william.plugins.lsp.mason")
require("william.plugins.lsp.lspsaga")
require("william.plugins.lsp.lspconfig")
require("william.plugins.lsp.null-ls")
require("william.plugins.autopairs")
require("william.plugins.treesitter")
require("william.plugins.gitsigns")
